# .github/workflows/delete-vm.yml

name: Destroy Google Cloud VM

on:
  workflow_dispatch:  # Trigger manually

jobs:
  destroy-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.0

      - name: Initialize Terraform
        run: terraform init -input=false

      - name: Plan to Destroy VM
        run: terraform plan -destroy -out=tfplan

      - name: Apply and Destroy VM
        run: terraform apply -auto-approve tfplan
