# .github/workflows/delete-vm.yml

name: Destroy Google Cloud VM

on:
  workflow_dispatch:  # Trigger manually

jobs:
  destroy-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.0

      # Authenticate with GCP using Base64 encoded secret
      - name: Authenticate with GCP
        run: |
          echo '${{ secrets.GCP_CREDENTIALS }}' | base64 --decode > terraform-key.json
          gcloud auth activate-service-account --key-file=terraform-key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud config set compute/zone ${{ secrets.GCP_ZONE }}


      - name: Initialize Terraform
        run: terraform init -input=false

      - name: Plan to Destroy VM
        run: terraform plan -destroy -out=tfplan

      - name: Apply and Destroy VM
        run: terraform apply -auto-approve tfplan
